gen-json ::
	cd .. && bun run gen:font-json -- k
	cd .. && bun run gen:font-json -- m3

maps_to_gif ::
	cd .. && bun run gen:maps-gif

missings_to_gif ::
	cd .. && bun run gen:missing-gif

missings_to_png ::
	cd .. && bun run gen:missing-png
