all: usrfont.24m usrfont.24k etp.xfn tsongyi.box

usrfont.24m: usrspell.24m usrother.24m
	merge -p -f cmex -o usrfont.24m usrother.24m usrspell.24m

usrspell.24m: usrfont.lst base8.raw
	spellgen -s 24 -t m -o usrspell.24m

usrother.24m: /font/oth.xfn
	resize -t m3 -i /font/oth.xfn -o usrother.24m

usrfont.24k: usrspell.24k usrhan.24k
	merge -p -f cmex -o usrfont.24k usrhan.24k usrspell.24k

usrspell.24k: usrfont.lst base8.raw
	spellgen -s 24 -t k -o usrspell.24k

usrhan.24k: /font/han.xfn
	resize -t k -i /font/han.xfn -o usrhan.24k

etp.xfn: spell.xfn /font/han.xfn /font/oth.xfn
	merge -f xfn -o etp.xfn spell.xfn /font/han.xfn /font/oth.xfn

spell.xfn: usrfont.lst base32.raw
	spellgen -s 96 -o spell.xfn

#tsongyi.box: usrfont.lst tsongyi.sup
#        perl tyimgen.pl
