/**
 * One-shot generator for lib/dic/cp950-table.ts (run before removing iconv-lite).
 * Usage: bun run scripts/gen-cp950-table.ts
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import iconv from "iconv-lite";

const ROOT = join(import.meta.dir, "..");
const OUT = join(ROOT, "lib/dic/cp950-table.ts");

function isCp950Trail(b: number): boolean {
  return (b >= 0x40 && b <= 0x7e) || (b >= 0xa1 && b <= 0xfe);
}

/** lead 0x81..0xFE → trail 0..255 → Unicode code point or 0 if unmapped */
const rows: number[][] = [];
let mapped = 0;

for (let lead = 0x81; lead <= 0xfe; lead++) {
  const row = new Array<number>(256).fill(0);
  for (let trail = 0; trail < 256; trail++) {
    if (!isCp950Trail(trail)) continue;
    const buf = Buffer.from([lead, trail]);
    const s = iconv.decode(buf, "cp950");
    if (s.length !== 1) continue;
    const cp = s.codePointAt(0)!;
    row[trail] = cp;
    mapped++;
  }
  rows.push(row);
}

const leadMin = 0x81;
const body = rows
  .map((row, i) => {
    const lead = leadMin + i;
    const nonZero = row
      .map((cp, trail) => (cp ? `0x${trail.toString(16)}:0x${cp.toString(16)}` : ""))
      .filter(Boolean);
    if (nonZero.length === 0) return "";
    return `  0x${lead.toString(16)}:{${nonZero.join(",")}}`;
  })
  .filter(Boolean)
  .join(",\n");

const src = `// Generated by scripts/gen-cp950-table.ts — do not edit by hand.
// CP950 lead (0x81–0xFE) + trail → Unicode scalar. Vendor + standard plane.

export const CP950_LEAD_MIN = 0x81 as const;
export const CP950_LEAD_MAX = 0xfe as const;

/** Sparse: lead byte → trail byte → code point */
export const CP950_BY_LEAD_TRAIL: Record<number, Record<number, number>> = {
${body},
};

export const CP950_PAIR_COUNT = ${mapped} as const;
`;

writeFileSync(OUT, src);
console.log(`Wrote ${OUT} (${mapped} pairs)`);